PizzaOrder/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaOrder.Data;
using PizzaOrder.Models;
using PizzaOrder.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NToastNotify;

namespace PizzaOrder.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public AdminController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }
        public IActionResult Index(string searchString)
        {
            var orders = from e in _context.Orders
                        select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(s => s.Surname!.Contains(searchString));
            }
            return View(orders);
        }
        public IActionResult AddNewFood()
        {
            FoodViewModel viewModel = new FoodViewModel()
            {
                Category = _context.Categories.Select(e => new SelectListItem() { Text = e.Name, Value = e.Id.ToString() })
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddNewFood(FoodViewModel model)
        {
            if(!ModelState.IsValid)
            {
                FoodViewModel viewModel = new FoodViewModel()
                {
                    Category = _context.Categories.Select(e => new SelectListItem() { Text = e.Name, Value = e.Id.ToString() })
                };
                return View(viewModel);
            }
            _context.Foods.Add(model.Food);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("New food was succesfully added!");

            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteFood(int? id)
        {
            if (id == null || id <= 0) return NotFound();
            var foodToRemove = _context.Foods.Find(id);
            if (foodToRemove == null) return NotFound();
            _context.Foods.Remove(foodToRemove);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Selected food was deleted");

            return RedirectToAction(nameof(ShowAllFoods));
        }
        public IActionResult EditFood(int? id)
        {
            if (id == null || id <= 0) return NotFound();

            var food = _context.Foods.Find(id);

            if (food == null) return NotFound();

            IEnumerable<SelectListItem> categories = _context.Categories.Select(e => new SelectListItem()
            { Text = e.Name, Value = e.Id.ToString() });
            ViewBag.CategoryList = categories;

            return View(food);
        }
        [HttpPost]
        public IActionResult EditFood(Food obj)
        {
            if (!ModelState.IsValid) return View();

            _context.Foods.Update(obj);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Selected food was edited.");

            return RedirectToAction(nameof(ShowAllFoods));
        }

        public IActionResult ShowAllFoods() => View(_context.Foods.ToList());
        public IActionResult ShowAllOrders() => View(_context.Orders.ToList());

    }
}

PizzaOrder/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using PizzaOrder.Data;
using PizzaOrder.Models;
using System.Collections.Generic;
using System.Linq;

namespace PizzaOrder.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategoryController : Controller
    {
        ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public CategoryController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }
        public IActionResult Index()
        {
            return View(_context.Categories.ToList());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (!ModelState.IsValid) return View();
            _context.Categories.Add(category);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("New category successfully created");

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound();
            var categoryToRemove = _context.Categories.Find(id);
            if (categoryToRemove == null) return NotFound();
            _context.Categories.Remove(categoryToRemove);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Category successfully deleted");

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id <= 0) return NotFound();

            var ganre = _context.Categories.Find(id);

            if (ganre == null) return NotFound();

            IEnumerable<SelectListItem> categories = _context.Categories.Select(i => new SelectListItem()
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });
            ViewBag.CategoryList = categories;

            return View(ganre);
        }

        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            if (!ModelState.IsValid) return View();

            _context.Categories.Update(obj);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Category successfully edited");

            return RedirectToAction(nameof(Index));
        }
    }
}

PizzaOrder/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PizzaOrder.Models;
using PizzaOrder.Models.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzaOrder.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var addedRoles = roles.Except(userRoles);
                // получаем роли, которые были удалены
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

PizzaOrder/Views/Admin/AddNewFood.cshtml
@model PizzaOrder.Models.ViewModel.FoodViewModel;

<div style="margin-top: 100px; color: white;">
    <form method="post" asp-action="AddNewFood">
        <h2 class="mb-3">Create a new product</h2>
        <div class="form-group row">
            <label asp-for="Food.Title" class="col-4"></label>
            <input id="modelInput" asp-for="Food.Title" class="form-control col-8">
            <span asp-validation-for="Food.Title" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="Food.Description" class="col-4"></label>
            <textarea asp-for="Food.Description" class="form-control col-8 summernote" style="background-color: black;color:#fff;"></textarea>
            <span asp-validation-for="Food.Description" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="Food.CategoryId" class="col-4"></label>
            <select asp-for="Food.CategoryId" asp-items="@Model.Category" class="col-8">
                <option disabled>--Select Category--</option>
            </select>
            <span asp-validation-for="Food.CategoryId" class="offset-4 text-danger"></span>
        </div>  
        <div class="form-group row">
            <label asp-for="Food.Price" class="col-4"></label>
            <input asp-for="Food.Price" class="form-control col-8">
            <span asp-validation-for="Food.Price" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="Food.Weight" class="col-4"></label>
            <input asp-for="Food.Weight" class="form-control col-8">
            <span asp-validation-for="Food.Weight" class="offset-4 text-danger"></span>
        </div>
         <div class="form-group row">
            <label asp-for="Food.Image" class="col-4"></label>
            <input asp-for="Food.Image" class="form-control col-8">
            <span asp-validation-for="Food.Image" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row mb-5">
            <a asp-controller="Category" class="col-6" asp-action="Index">Edit categories</a>
        </div>
        <div class="form-group row">
            <div class="col-6">
                <input type="submit" onclick="validateInputs()" class="btn btn-success w-100" value="Create" />
            </div>
            <div class="col-6">
                <a asp-action="Index" class="btn btn-dark w-100">Back</a>
            </div>
        </div>
    </form>
</div>

@* Client Validation *@
@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial.cshtml"/> }
    <script>
        function validateInputs() {
            const modelInput = document.getElementById("modelInput");
            if (modelInput.value == "") {
                Swal.fire({
                    title: 'Error!',
                    text: 'You must enter a valid model!',
                    icon: 'error',
                    confirmButtonText: 'Ok'
                });
            }
        }
        $(document).ready(function () {
            $('.summernote').summernote({
                height: 100
            });
        });
    </script>
}

PizzaOrder/Views/Admin/EditFood.cshtml
@model PizzaOrder.Models.Food;

@{
    ViewData["Title"] = "Edit Food";
}

<div style="margin-top: 100px;">
    <form method="post" asp-action="EditFood">
        <h2 class="mb-3">Create a new track</h2>
        <div class="form-group row">
            <label asp-for="Title" class="col-4"></label>
            <input id="modelInput" asp-for="Title" class="form-control col-8">
            <span asp-validation-for="Title" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="Description" class="col-4"></label>
            <input asp-for="Description" class="form-control col-8">
            <span asp-validation-for="Description" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="CategoryId" class="col-4"></label>
            <select asp-for="CategoryId" asp-items="@ViewBag.CategoryList" class="col-8">
                <option disabled>--Select Category--</option>
            </select>
            <span asp-validation-for="CategoryId" class="offset-4 text-danger"></span>
        </div>  
        <div class="form-group row">
            <label asp-for="Price" class="col-4"></label>
            <input asp-for="Price" class="form-control col-8">
            <span asp-validation-for="Price" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row">
            <label asp-for="Weight" class="col-4"></label>
            <input asp-for="Weight" class="form-control col-8">
            <span asp-validation-for="Weight" class="offset-4 text-danger"></span>
        </div>
         <div class="form-group row">
            <label asp-for="Image" class="col-4"></label>
            <input asp-for="Image" class="form-control col-8">
            <span asp-validation-for="Image" class="offset-4 text-danger"></span>
        </div>
        <div class="form-group row mb-5">
            <a asp-controller="Category" class="col-6" asp-action="Index">Edit categories</a>
        </div>
        <div class="form-group row">
            <div class="col-6">
                <input type="submit" onclick="validateInputs()" class="btn btn-success w-100" value="Update" />
            </div>
            <div class="col-6">
                <a asp-action="Index" class="btn btn-dark w-100">Back</a>
            </div>
        </div>
    </form>
</div>

@* Client Validation *@
@section Scripts
{
    @{ <partial name="_ValidationScriptsPartial.cshtml"/> }
}

PizzaOrder/Views/Admin/Index.cshtml
@{
}
<div style="display:flex; flex-direction: column; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
    <h1 class="mb-5" style="
     color: white;">
        Menu of admin's site
    </h1>
    <div class="mb-2 text-left" style="display:flex; flex-direction: column;">
        <a asp-controller="Admin" asp-action="AddNewFood" class="btn btn-primary mb-3">Add new product</a>
        <a asp-controller="Admin" asp-action="ShowAllFoods" class="btn btn-primary mb-3">Product list</a>
        <a asp-controller="Admin" asp-action="ShowAllOrders" class="btn btn-primary mb-3">Order list</a>
        <a asp-controller="Category" asp-action="Create" class="btn btn-primary mb-3">Create new category</a>
        <a asp-area="" asp-controller="Category" asp-action="Index" class="btn btn-primary mb-3">List of exists category</a>
        <a asp-area="" asp-controller="Roles" asp-action="Index" class="btn btn-primary mb-3">Role manegment</a>
    </div>
</div>


@* Client Validation *@
@section Scripts {
<script>

</script>
}

PizzaOrder/Views/Admin/ShowAllFood.cshtml
@model IEnumerable<PizzaOrder.Models.Food>

@{
    ViewData["Title"] = "All foods";
}

<div>
    <h1>All foods</h1>
    <table class="table">
        <thead>
            <tr>
                <td class="font-weight-bold" scope="col">Title</td>
                <td class="font-weight-bold" scope="col">Description</td>
                <td class="font-weight-bold" scope="col">Weight</td>
                <td class="font-weight-bold" scope="col">Price</td>
                <td class="font-weight-bold" scope="col">Image</td>
                <td class="font-weight-bold" scope="col">Action</td>
            </tr>
        </thead>
        <tbody>
            @foreach (var food in Model)
            {
                <tr>
                    <td>@food.Title</td>
                    <td>@food.Description</td>
                    <td>@food.Weight</td>
                    <td>@food.Price</td>
                    <td><img src="@food.Image" width="100px" height="50px"></td>
                    <td>
                        <div class="btn-group">
                            <a asp-controller="Admin" asp-action="EditFood" asp-route-id="@food.Id" class="btn btn-secondary">Edit</a>
                            <a asp-controller="Admin" asp-action="DeleteFood" onclick="confirmDelete()" asp-route-id="@food.Id" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

PizzaOrder/Views/Admin/ShowAllOrders.cshtml
@model IEnumerable<PizzaOrder.Models.Order>

<h1 class="mb-5">All orders</h1>
<div style="display: flex; flex-direction: row; gap: 30px; flex-wrap: wrap;">
    @if (Model.Any())
    {
        @foreach (var order in Model)
        {
            <partial name="_OrderCartPartial" model="@order" />
        }
    }
    else
    {
        <h1>List is empty!</h1>
    }
</div>