PizzaOrder/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzaOrder.Data;
using PizzaOrder.Models;
using PizzaOrder.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using NToastNotify;

namespace PizzaOrder.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        ApplicationDbContext _context;
        private readonly IToastNotification _toastNotification;
        public AdminController(ApplicationDbContext context, IToastNotification toastNotification)
        {
            _context = context;
            _toastNotification = toastNotification;
        }
        public IActionResult Index(string searchString)
        {
            var orders = from e in _context.Orders
                        select e;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(s => s.Surname!.Contains(searchString));
            }
            return View(orders);
        }
        public IActionResult AddNewFood()
        {
            FoodViewModel viewModel = new FoodViewModel()
            {
                Category = _context.Categories.Select(e => new SelectListItem() { Text = e.Name, Value = e.Id.ToString() })
            };

            return View(viewModel);
        }
        [HttpPost]
        public IActionResult AddNewFood(FoodViewModel model)
        {
            if(!ModelState.IsValid)
            {
                FoodViewModel viewModel = new FoodViewModel()
                {
                    Category = _context.Categories.Select(e => new SelectListItem() { Text = e.Name, Value = e.Id.ToString() })
                };
                return View(viewModel);
            }
            _context.Foods.Add(model.Food);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("New food was succesfully added!");

            return RedirectToAction(nameof(Index));
        }
        public IActionResult DeleteFood(int? id)
        {
            if (id == null || id <= 0) return NotFound();
            var foodToRemove = _context.Foods.Find(id);
            if (foodToRemove == null) return NotFound();
            _context.Foods.Remove(foodToRemove);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Selected food was deleted");

            return RedirectToAction(nameof(ShowAllFoods));
        }
        public IActionResult EditFood(int? id)
        {
            if (id == null || id <= 0) return NotFound();

            var food = _context.Foods.Find(id);

            if (food == null) return NotFound();

            IEnumerable<SelectListItem> categories = _context.Categories.Select(e => new SelectListItem()
            { Text = e.Name, Value = e.Id.ToString() });
            ViewBag.CategoryList = categories;

            return View(food);
        }
        [HttpPost]
        public IActionResult EditFood(Food obj)
        {
            if (!ModelState.IsValid) return View();

            _context.Foods.Update(obj);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Selected food was edited.");

            return RedirectToAction(nameof(ShowAllFoods));
        }

        public IActionResult ShowAllFoods() => View(_context.Foods.ToList());
        public IActionResult ShowAllOrders() => View(_context.Orders.ToList());

    }
}

PizzaOrder/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using PizzaOrder.Data;
using PizzaOrder.Helpers;
using PizzaOrder.Models;
using PizzaOrder.Models.ViewModel;
using System.Collections.Generic;
using System.Linq;

namespace PizzaOrder.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly IViewRender _viewRender;
        private readonly IHttpContextAccessor _session;

        public CartController(ApplicationDbContext context, 
            IEmailSender emailSender, 
            IViewRender viewRender,
            IHttpContextAccessor session)
        {
            _context = context;
            _emailSender = emailSender;
            _viewRender = viewRender;
            _session = session;
        }
        
        [AllowAnonymous]
        public IActionResult Index()
        {
            CartListViewModel viewModel = new CartListViewModel()
            {
                Foods = GetFoodsFromSession()
            };
            return View(viewModel);
        }
        private IEnumerable<Food> GetFoodsFromSession()
        {
            List<ShoppingOrder> products = HttpContext.Session.GetObject<List<ShoppingOrder>>("ShoppingOrders");
            if (products == null)
                products = new List<ShoppingOrder>();

            int[] productIds = products.Select(i => i.FoodId).ToArray();

            return _context.Foods.Where(c => productIds.Contains(c.Id));
        }

        public IActionResult ClearCart()
        {
            _session.HttpContext.Session.Clear();
            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }

        // no need
        public IActionResult Confirm()
        {
            //string userEmail = User.Identity.Name;
            //var items = GetFoodsFromSession();

            //var html = this._viewRender.Render("Mails/OrderSummary", new OrderSummaryMail
            //{
            //    UserName = userEmail,
            //    Foods = items,
            //    TotalPrice = items.Sum(i => i.Price)
            //});

            //_emailSender.SendEmailAsync(userEmail, "Order Summary", html);

            return View();
        }
    }
}

PizzaOrder/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using PizzaOrder.Data;
using PizzaOrder.Helpers;
using PizzaOrder.Models;
using PizzaOrder.Models.ViewModel;
using System.Collections.Generic;
using System.Linq;

namespace PizzaOrder.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly IViewRender _viewRender;
        private readonly IToastNotification _toastNotification;
        public OrderController(ApplicationDbContext context, 
            IEmailSender emailSender,
            IViewRender viewRender,
            IToastNotification toastNotification)
        {
            _context = context;
            _emailSender = emailSender;
            _viewRender = viewRender;
            _toastNotification = toastNotification;
        }
        public IActionResult Index()
        {
            return View(_context.Orders.Include(nameof(Order.Food)));
        }
        public IActionResult AddOrder()
        {
            IEnumerable<SelectListItem> foods = _context.Foods.Select(e => new SelectListItem()
            { Text = e.Title, Value = e.Id.ToString() });
            ViewBag.FoodList = foods;

            return View();
        }
        private IEnumerable<Food> GetFoodsFromSession()
        {
            List<ShoppingOrder> products = HttpContext.Session.GetObject<List<ShoppingOrder>>("ShoppingOrders");
            if (products == null)
                products = new List<ShoppingOrder>();

            int[] productIds = products.Select(i => i.FoodId).ToArray();

            return _context.Foods.Where(c => productIds.Contains(c.Id));
        }
        [HttpPost]
        public IActionResult AddOrder(Order newOrder)
        {
            if (!ModelState.IsValid) return View();
            _context.Orders.Add(newOrder);
            _context.SaveChanges();

            string userEmail = User.Identity.Name;
            var items = GetFoodsFromSession();

            var html = this._viewRender.Render("Mails/OrderSummary", new OrderMail
            {
                UserName = userEmail,
                Foods = items,
                TotalPrice = items.Sum(i => i.Price)
            });

            _emailSender.SendEmailAsync(userEmail, "Order Summary", html);

            _toastNotification.AddSuccessToastMessage("Order was added. </br> Check your email");

            return RedirectToRoute(new { controller = "Home", action = "Index" });
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id <= 0) return NotFound();
            var orderToRemove = _context.Orders.Find(id);
            if (orderToRemove == null) return NotFound();
            _context.Orders.Remove(orderToRemove);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Order was deleted.");

            return RedirectToAction(nameof(Index)); // back to Index 
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id <= 0) return NotFound();

            var order = _context.Orders.Find(id);

            if (order == null) return NotFound();

            return View(order);
        }

        [HttpPost]
        public IActionResult Edit(Order obj)
        {
            if (!ModelState.IsValid) return View();

            _context.Orders.Update(obj);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Order was edited.");

            return RedirectToAction(nameof(Index));
        }
    }
}

PizzaOrder/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@using PizzaOrder.Helpers
@using PizzaOrder.Models
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IHttpContextAccessor HttpContextAccessor;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaOrder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Product.css   />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/fontawesome/css/all.css" rel="stylesheet" />
    <style>
        body {
            width: 100%;
            height: 100%;
            background-color: black;
            background-image: url("https://images.unsplash.com/photo-1513104890138-7c749659a591?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80");
            background-position: center;
            background-size: cover;
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
        }
    </style>
</head>
<body>
    <header style="margin-bottom: 100px;">

        <nav class="navbar navbar-expand-lg navbar-light shadow-sm bg-light fixed-top">
            <div class="container" style="font-weight: bold">
                <a class="navbar-brand d-flex align-items-center" asp-controller="Home" asp-action="Index">
                    <span class="ml-3 font-weight-bold" style="">Pizza Order</span>
                </a> <button class="navbar-toggler navbar-toggler-right border-0" type="button" data-toggle="collapse" data-target="#navbar4">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbar4">
                    <ul class="navbar-nav mr-auto pl-lg-4">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                    ORDER
                                    @{
                                        var list = HttpContextAccessor.HttpContext.Session
                .GetObject<IEnumerable<Order>>("ShoppingOrders");
                                        var count = list != null ? list.Count() : 0;
                                    }
                                    (@count)
                                </a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">DELIVERY AND PAYMENT</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">CONTACTS</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">ADMIN</a>
                            </li>
                        }
                    </ul>
                    <div class="d-flex justify-content-around">
                        <div>
                            <form asp-controller="Home" asp-action="Index" class="d-flex" style="width: 100%;">
                                <input class="form-control me-sm-2" type="text" name="SearchString" placeholder="Searching... ">
                                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </div>
                        <div class="d-flex align-items-start">
                            <ul class="navbar-nav mr-auto pl-lg-4">
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">
                                            <img src="~/image/user.png">
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button type="submit" class="nav-link btn btn-link text-dark">
                                                <img src="~/image/logout.png">
                                            </button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Registration</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @await Component.InvokeAsync("NToastNotify")
        </main>
    </div>

    <footer class="border-top footer bg-light">
        <div class="container">
            &copy; 2022 <a asp-area="" asp-controller="Home" asp-action="AboutCreator">All rights reserved.</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

PizzaOrder/Views/Shared/_MailLayout.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="x-apple-disable-message-reformatting">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mail Layout</title>
    <link href="https://fonts.googleapis.com/css?family=Cabin:400,700&display=swap" rel="stylesheet" type="text/css">
</head>

<body class="clean-body u_body" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;background-color: #ffffff;color: #000000; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
    @RenderBody()
</body>

</html>

PizzaOrder/Views/Shared/_OrderCartPartial.cshtml
@model PizzaOrder.Models.Order
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<div class="card" style="width: 18rem; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
    <div class="card-body">
        <h5 class="card-title"><span class="font-weight-bold">Name:</span> @Model.Name</h5>
        <h5 class="card-title"><span class="font-weight-bold">Surname:</span> @Model.Surname</h5>
        <h5 class="card-title"><span class="font-weight-bold">Phone:</span> @Model.Phone</h5>
        <h5 class="card-title"><span class="font-weight-bold">Address:</span> @Model.Address</h5>
        <h5 class="card-title">
            <span class="font-weight-bold">Order:</span>
            @if (Model.Food != null)
            {
                @Model.Food.Title
            }
        </h5>
        @if (Model.NonCashCalculation == true)
        {
            <h5 class="card-title"><span class="font-weight-bold">Type of payment:</span> cash</h5>
        }
        @if (Model.CashSettlement == true)
        {
            <h5 class="card-title"><span class="font-weight-bold">Type of payment:</span> card</h5>
        }
    </div>
    <div class="btn-group">
        @if (User.IsInRole("admin"))
        {
            <a asp-controller="Order" asp-action="Delete" asp-route-id="@Model.OrderId" class="btn btn-danger">Delete</a>
            <a asp-controller="Order" asp-action="Edit" asp-route-id="@Model.OrderId" class="btn btn-danger">Edit</a>
        }
    </div>
</div>

PizzaOrder/Views/Shared/_PizzaCartPartial.cshtml
@model PizzaOrder.Models.Food
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager


<link href="@Url.Content("~/css/Product.css")" rel="stylesheet" type="text/css" />



<div class="modal fade" id="image-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" style="position: relative; font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
            <div class="modal-body" style="display: flex; align-items: center; flex-direction:column; justify-content: center;">
                <img class="img-responsive center-block" src="" alt="" style="max-width: 600px;">
            </div>
        </div>
    </div>
</div>
<div id="pizza-cart" class="border" style="
background-color: #E5E7E9;
min-width:250px;
font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px, rgba(10, 37, 64, 0.35) 0px -2px 6px 0px inset;">
    
    <a href="#" class="" style="position: relative; width: 100%; height: 100%; box-sizing: border-box;">
        <img src="@Model.Image" alt="..." style="width: 100%; height: 150px;">
    </a>
    <div class="p-3">
        <div class="">
            <h3 class="font-weight-bold text-dark d-flex justify-content-center">@Model.Title</h3>
            <div class="d-flex flex-lg-row" style="font-size: 20px">
                <p class="card-text font-weight-bold text-dark" style="font-size: 14px"><span class="text-danger">@Model.Weight</span> гр &nbsp;&nbsp;</p>
                <p class="card-text text-dark" style="font-size: 14px">@Model.Description</p>
            </div>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <p class="card-text font-weight-bold text-dark" style="font-size: 14px; margin-left: 5%"><span class="text-danger" style="font-size: 30px">@Model.Price</span> грн.</p>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="btn-group">
                    <a asp-controller="Home" asp-action="FoodDetails" asp-route-id="@Model.Id" class="btn btn-dark" style="height: 40px;">
                        <img src="~/image/basket.png">
                    </a>
                </div>
            }
        </div>

    </div>
    
</div>

@section Styles {
    <link href="@Url.Content("~/css/Product.css")" rel="stylesheet" type="text/css" />
}

PizzaOrder/Views/Shared/_ToasterPartial.cshtml
@if (@TempData["ErrorMessage"] != null)
{
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

        <script type="text/javascript">
            const Toast = Swal.mixin({
            toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                            didOpen: (toast) =>
                            {
                                toast.addEventListener('mouseenter', Swal.stopTimer)
                                toast.addEventListener('mouseleave', Swal.resumeTimer)
                            }})
            Toast.fire({
            icon: 'error',
                title: '@TempData["ErrorMessage"]'
            })
        </script>
}